/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import javax.swing.DefaultComboBoxModel;
import classesdedados.Telefone;
import classesdedados.Email;
import classesdedados.Endereco;
import classesdedados.Mensagens;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import persistencia.PessoaDAO;
import classesdedados.Pessoa;
import classesdedados.PessoaFisica;
import classesdedados.PessoaJuridica;
import classesdedados.Telefone.EnumTelefone;
import java.io.IOException;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renatowsilva
 */
public class TelaClienteCadastro extends javax.swing.JInternalFrame {

    ArrayList<Email> emails = new ArrayList<>();
    ArrayList<Telefone> telefones = new ArrayList<>();
    ArrayList<Endereco> enderecos = new ArrayList<>();

    /**
     * Creates new form TelaCadastroDeCliente2
     */
    public TelaClienteCadastro() {
        initComponents();
        jComboBoxTiposDeTelefones1.setModel(new DefaultComboBoxModel(Telefone.EnumTelefone.values()));
        jComboBoxCatCNH.setModel(new DefaultComboBoxModel(PessoaFisica.EnumCnh.values()));
        jComboBoxSexo.setModel(new DefaultComboBoxModel(PessoaFisica.EnumSexo.values()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCatCNH = new javax.swing.JComboBox<>();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonClienteSalvar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldDDI1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTelefone = new javax.swing.JTable();
        jTextFieldNumeroTelefone1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldDDD1 = new javax.swing.JTextField();
        jButtonIncluirTelefone1 = new javax.swing.JButton();
        jButtonExcluirTelefone1 = new javax.swing.JButton();
        jComboBoxTiposDeTelefones1 = new javax.swing.JComboBox<>();
        jPanel2Email1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEmail = new javax.swing.JTable();
        jButtonIncluirEmail1 = new javax.swing.JButton();
        jButtonExcluirEmail1 = new javax.swing.JButton();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonIncluirEndereco1 = new javax.swing.JButton();
        jButtonExcluirEndereco1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableEndereco = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jFormattedTextFieldEndNumero = new javax.swing.JFormattedTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldComplento = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        jFormattedTextFieldValidadeCNH = new javax.swing.JFormattedTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jFormattedTextFieldCNH = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyReleased(evt);
            }
        });

        jLabel8.setText("Nome Completo:");

        jButtonClienteSalvar1.setText("SALVAR");
        jButtonClienteSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteSalvar1ActionPerformed(evt);
            }
        });

        jLabel21.setText("N° CNH:");

        jLabel22.setText("Categoria:");

        jLabel23.setText("CPF:");

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldDDI1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTableTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDI", "DDD", "Número", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefoneMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTelefone);

        jTextFieldNumeroTelefone1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setText("DDI");

        jLabel25.setText("NÚMERO");

        jLabel26.setText("DDD");

        jLabel27.setText("TIPO");

        jTextFieldDDD1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonIncluirTelefone1.setText("INCLUIR");
        jButtonIncluirTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirTelefone1ActionPerformed(evt);
            }
        });

        jButtonExcluirTelefone1.setText("EXCLUIR");
        jButtonExcluirTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTelefone1ActionPerformed(evt);
            }
        });

        jComboBoxTiposDeTelefones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTiposDeTelefones1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldDDI1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jTextFieldDDD1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldNumeroTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTiposDeTelefones1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonIncluirTelefone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirTelefone1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDDI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDDD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxTiposDeTelefones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirTelefone1)
                    .addComponent(jButtonExcluirTelefone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Telefone", jPanel5);

        jTableEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmailMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableEmail);

        jButtonIncluirEmail1.setText("INCLUIR");
        jButtonIncluirEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEmail1ActionPerformed(evt);
            }
        });

        jButtonExcluirEmail1.setText("EXCLUIR");
        jButtonExcluirEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEmail1ActionPerformed(evt);
            }
        });

        jTextFieldEmail1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmail1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Email");

        javax.swing.GroupLayout jPanel2Email1Layout = new javax.swing.GroupLayout(jPanel2Email1);
        jPanel2Email1.setLayout(jPanel2Email1Layout);
        jPanel2Email1Layout.setHorizontalGroup(
            jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Email1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Email1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                                .addComponent(jButtonIncluirEmail1)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonExcluirEmail1))
                            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Email1Layout.setVerticalGroup(
            jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIncluirEmail1)
                    .addComponent(jButtonExcluirEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Email", jPanel2Email1);

        jButtonIncluirEndereco1.setText("INCLUIR");
        jButtonIncluirEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEndereco1ActionPerformed(evt);
            }
        });

        jButtonExcluirEndereco1.setText("EXCLUIR");
        jButtonExcluirEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEndereco1ActionPerformed(evt);
            }
        });

        jLabel29.setText("Lougradouro");

        jLabel30.setText("Numero");

        jTableEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lougradouro", "Numero", "Bairro", "Cidade", "Estado", "Pais", "Cep", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnderecoMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTableEndereco);

        jLabel31.setText("CEP");

        jLabel32.setText("Cidade");

        jLabel33.setText("Estado");

        jLabel34.setText("Pais");

        jLabel35.setText("Bairro");

        jLabel36.setText("Complemento");

        try {
            jFormattedTextFieldEndNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEndNumero.setText("");

        jTextFieldPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaisActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonIncluirEndereco1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluirEndereco1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLogradouro)
                                    .addComponent(jTextFieldComplento))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jFormattedTextFieldEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextFieldComplento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel32)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirEndereco1)
                    .addComponent(jButtonIncluirEndereco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldBairro, jTextFieldComplento, jTextFieldEstado, jTextFieldLogradouro});

        jTabbedPane1.addTab("Endereço", jPanel6);

        jLabel24.setText("Data de Nasc.:");

        try {
            jFormattedTextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel37.setText("Validade");

        try {
            jFormattedTextFieldValidadeCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel38.setText("Sexo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxCatCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonClienteSalvar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxCatCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jFormattedTextFieldValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClienteSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    public void limparTela() {
        //cria os objetos tabelas
        DefaultTableModel dtmEmail = (DefaultTableModel) jTableEmail.getModel();
        DefaultTableModel dtmEnd = (DefaultTableModel) jTableEndereco.getModel();
        DefaultTableModel dtmTel = (DefaultTableModel) jTableTelefone.getModel();

        //limpa as tabelas
        dtmEmail.setRowCount(0);
        dtmEnd.setRowCount(0);
        dtmTel.setRowCount(0);

        //limpa as caixas de textos, combobox e campos formatados
        jTextFieldNome.setText("");
        jFormattedTextFieldCNH.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldValidadeCNH.setText("");

        //limpa as caixas de textos de endereço
        jTextFieldLogradouro.setText("");
        jFormattedTextFieldEndNumero.setText("");
        jTextFieldComplento.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldPais.setText("");
        jFormattedTextFieldCEP.setText("");
    }

    private void jButtonClienteSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteSalvar1ActionPerformed
        PessoaFisica pessoaFisica = new PessoaFisica();
        PessoaDAO contatos = new PessoaDAO();

        try {
            pessoaFisica.setNome(jTextFieldNome.getText().toUpperCase());
            pessoaFisica.setDataDeNasc(jFormattedTextFieldDataNascimento.getText());
            pessoaFisica.setValidadeCnh(jFormattedTextFieldValidadeCNH.getText());
            pessoaFisica.setTipo(Pessoa.EnumPessoa.FISICA);
            pessoaFisica.setCpf(jFormattedTextFieldCPF.getText());
            pessoaFisica.setCnh(jFormattedTextFieldCNH.getText());
            pessoaFisica.setCategoriaCnh(Enum.valueOf(PessoaFisica.EnumCnh.class, jComboBoxCatCNH.getSelectedItem().toString()));
            pessoaFisica.setSexo(Enum.valueOf(PessoaFisica.EnumSexo.class, jComboBoxSexo.getSelectedItem().toString()));

            pessoaFisica.setTelefone(telefones);
            pessoaFisica.setEmail(emails);
            pessoaFisica.setEndereco(enderecos);

            if (jTextFieldNome.getText().equals("")) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTextFieldNome.requestFocus();
                return;
            }
            if (telefones.size() <= 0) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTabbedPane1.setSelectedIndex(0);
                jTextFieldDDI1.requestFocus();
                return;
            }
            if (emails.size() <= 0) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTabbedPane1.setSelectedIndex(1);
                jTextFieldEmail1.requestFocus();
                return;
            }

            contatos.incluir(pessoaFisica);
            limparTela();
            telefones.clear();
            emails.clear();
            enderecos.clear();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
        }
    }//GEN-LAST:event_jButtonClienteSalvar1ActionPerformed

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jTableTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefoneMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableTelefone.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableTelefone.getSelectedRow() >= 0) {
                    jTextFieldDDI1.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jTextFieldDDD1.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldNumeroTelefone1.setText(String.valueOf(dtm.getValueAt(idx, 2)));

                    dtm.removeRow(idx);
                    telefones.remove(idx);

                    jTextFieldDDI1.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG18"));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableTelefoneMouseClicked

    private void jButtonIncluirTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirTelefone1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        Telefone telefone = new Telefone();
        String strDDI = jTextFieldDDI1.getText();
        String strDDD = jTextFieldDDD1.getText();
        String strNum = jTextFieldNumeroTelefone1.getText();

        if (!jTextFieldDDI1.getText().equals("") && !jTextFieldDDD1.getText().equals("") && !jTextFieldNumeroTelefone1.getText().equals("")) {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(strDDI)
                            && String.valueOf(dtm.getValueAt(i, 1)).equals(strDDD)
                            && String.valueOf(dtm.getValueAt(i, 2)).equals(strNum)) {
                        JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG19"));
                        jTextFieldDDI1.requestFocus();
                        return;
                    }
                }
            }
            try {
                if (jTextFieldDDI1.getText().length() <= 3) {
                    try {
                        telefone.setDdi(Integer.parseInt(jTextFieldDDI1.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldDDI1.setText("");
                        jTextFieldDDI1.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldDDI1.requestFocus();
                    return;
                }

                if (jTextFieldDDD1.getText().length() <= 3) {
                    try {
                        telefone.setDdd(Integer.parseInt(jTextFieldDDD1.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldDDD1.setText("");
                        jTextFieldDDD1.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldDDD1.requestFocus();
                    return;
                }

                if (jTextFieldNumeroTelefone1.getText().length() <= 10) {
                    try {
                        telefone.setNumero(Integer.parseInt(jTextFieldNumeroTelefone1.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldNumeroTelefone1.setText("");
                        jTextFieldNumeroTelefone1.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldNumeroTelefone1.requestFocus();
                    return;
                }

                telefone.setTipo((EnumTelefone) jComboBoxTiposDeTelefones1.getSelectedItem());
                telefones.add(telefone);
                Object[] dados = {jTextFieldDDI1.getText(), jTextFieldDDD1.getText(), jTextFieldNumeroTelefone1.getText(),
                    jComboBoxTiposDeTelefones1.getSelectedItem()};
                dtm.addRow(dados);

                jTextFieldDDI1.setText("");
                jTextFieldDDD1.setText("");
                jTextFieldNumeroTelefone1.setText("");
                jTextFieldDDI1.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
        }
    }//GEN-LAST:event_jButtonIncluirTelefone1ActionPerformed

    private void jButtonExcluirTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTelefone1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();

        try {
            int idx[] = jTableTelefone.getSelectedRows();
            if (jTableTelefone.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    telefones.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG18"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirTelefone1ActionPerformed

    private void jComboBoxTiposDeTelefones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTiposDeTelefones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTiposDeTelefones1ActionPerformed

    private void jTableEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmailMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEmail.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEmail.getSelectedRow() >= 0) {
                    jTextFieldEmail1.setText(String.valueOf(dtm.getValueAt(idx, 0)));

                    dtm.removeRow(idx);
                    emails.remove(idx);

                    jTextFieldEmail1.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEmailMouseClicked

    private void jButtonIncluirEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEmail1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail.getModel();
        Email email = new Email();
        String campoEmail = jTextFieldEmail1.getText();

        try {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(campoEmail)) {
                        JOptionPane.showMessageDialog(this, "Email já informado para este contato");
                        jTextFieldEmail1.requestFocus();
                        return;
                    }
                }
            }

            if (!campoEmail.equals("")) {
                email.setEmail(campoEmail);
                emails.add(email);
                Object[] dados = {campoEmail};
                dtm.addRow(dados);

                jTextFieldEmail1.setText("");
                jTextFieldEmail1.requestFocus(); //coloca o cursor na caixa de texto
            } else {
                JOptionPane.showMessageDialog(null, "Informe o e-mail.");
                jTextFieldEmail1.requestFocus(); //coloca o cursor na caixa de texto
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEmail1ActionPerformed

    private void jButtonExcluirEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEmail1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail.getModel();

        try {
            int idx[] = jTableEmail.getSelectedRows();
            if (jTableEmail.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    emails.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEmail1ActionPerformed

    private void jTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1ActionPerformed

    private void jButtonIncluirEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEndereco1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();
        Endereco endereco = new Endereco();
        int numeroEndereco = 0;
        int cep = 0;

        try {
            String logradouro = jTextFieldLogradouro.getText();
            String bairro = jTextFieldBairro.getText();
            String cidade = jTextFieldCidade.getText();
            String estado = jTextFieldEstado.getText();
            String pais = jTextFieldPais.getText();
            String complemento = jTextFieldComplento.getText();

            if (!logradouro.equals("") && !jFormattedTextFieldEndNumero.getText().equals("") && !bairro.equals("")
                    && !cidade.equals("") && !estado.equals("") && !pais.equals("")) {
                try {
                    numeroEndereco = Integer.parseInt(jFormattedTextFieldEndNumero.getText());
                    cep = Integer.parseInt(jFormattedTextFieldCEP.getText().replaceAll("-", ""));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro de conversão de dados.");
                    jFormattedTextFieldEndNumero.setText("");
                    jFormattedTextFieldEndNumero.requestFocus();
                    return;
                }

                try {
                    endereco.setLogradouro(logradouro);
                    endereco.setNumero(numeroEndereco);
                    endereco.setBairro(bairro);
                    endereco.setCidade(cidade);
                    endereco.setEstado(estado);
                    endereco.setPais(pais);
                    endereco.setCep(cep);
                    endereco.setComplemento(complemento);
                    enderecos.add(endereco);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                Object[] dados = {logradouro, String.valueOf(numeroEndereco), bairro, cidade, estado, pais, cep, complemento};
                dtm.addRow(dados);

                jTextFieldLogradouro.setText("");
                jFormattedTextFieldEndNumero.setText("");
                jTextFieldBairro.setText("");
                jTextFieldCidade.setText("");
                jTextFieldEstado.setText("");
                jTextFieldPais.setText("");
                jFormattedTextFieldCEP.setText("");
                jTextFieldComplento.setText("");

                jFormattedTextFieldEndNumero.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "Existem campos obrigórios que não foram preenchidos.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEndereco1ActionPerformed

    private void jButtonExcluirEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEndereco1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();

        try {
            int idx[] = jTableEndereco.getSelectedRows();
            if (jTableEndereco.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    enderecos.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEndereco1ActionPerformed

    private void jTableEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnderecoMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEndereco.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEndereco.getSelectedRow() >= 0) {
                    jTextFieldLogradouro.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jFormattedTextFieldEndNumero.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldBairro.setText(String.valueOf(dtm.getValueAt(idx, 2)));
                    jTextFieldCidade.setText(String.valueOf(dtm.getValueAt(idx, 3)));
                    jTextFieldPais.setText(String.valueOf(dtm.getValueAt(idx, 4)));
                    jTextFieldEstado.setText(String.valueOf(dtm.getValueAt(idx, 5)));
                    jFormattedTextFieldCEP.setText(String.valueOf(dtm.getValueAt(idx, 6)));
                    jTextFieldComplento.setText(String.valueOf(dtm.getValueAt(idx, 7)));

                    dtm.removeRow(idx);
                    enderecos.remove(idx);

                    jTextFieldLogradouro.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEnderecoMouseClicked

    private void jTextFieldNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyReleased
        jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
    }//GEN-LAST:event_jTextFieldNomeKeyReleased

    private void jTextFieldPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClienteSalvar1;
    private javax.swing.JButton jButtonExcluirEmail1;
    private javax.swing.JButton jButtonExcluirEndereco1;
    private javax.swing.JButton jButtonExcluirTelefone1;
    private javax.swing.JButton jButtonIncluirEmail1;
    private javax.swing.JButton jButtonIncluirEndereco1;
    private javax.swing.JButton jButtonIncluirTelefone1;
    private javax.swing.JComboBox<String> jComboBoxCatCNH;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTiposDeTelefones1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JTextField jFormattedTextFieldCNH;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldEndNumero;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidadeCNH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2Email1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEmail;
    private javax.swing.JTable jTableEndereco;
    private javax.swing.JTable jTableTelefone;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplento;
    private javax.swing.JTextField jTextFieldDDD1;
    private javax.swing.JTextField jTextFieldDDI1;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumeroTelefone1;
    private javax.swing.JTextField jTextFieldPais;
    // End of variables declaration//GEN-END:variables
}
