/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import classesdedados.Email;
import classesdedados.Endereco;
import classesdedados.Mensagens;
import classesdedados.Pessoa;
import classesdedados.PessoaFisica;
import classesdedados.Telefone;
import classesdedados.Telefone.EnumTelefone;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.PessoaDAO;

/**
 *
 * @author renatowsilva
 */
public class TelaClientePesquisa extends javax.swing.JInternalFrame {

    PessoaDAO dao = new PessoaDAO();
    ArrayList<PessoaFisica> alPessoaFisica = new ArrayList<>();
    ArrayList<Email> emails = new ArrayList<>();
    ArrayList<Telefone> telefones = new ArrayList<>();
    ArrayList<Endereco> enderecos = new ArrayList<>();
    PessoaFisica pessoaFisica = new PessoaFisica();

    /**
     * Creates new form TelaPesquisaCliente
     */
    public TelaClientePesquisa() throws Exception {
        initComponents();

        Object objDAO = dao.recuperar();
        alPessoaFisica = (ArrayList<PessoaFisica>) objDAO;

        jComboBoxTiposDeTelefones1.setModel(new DefaultComboBoxModel(Telefone.EnumTelefone.values()));
        jComboBoxCategoriaCNH.setModel(new DefaultComboBoxModel(PessoaFisica.EnumCnh.values()));
        jComboBoxSexo.setModel(new DefaultComboBoxModel(PessoaFisica.EnumSexo.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarCliente = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jComboBoxTipoDaPesquisa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldDDI1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTelefone = new javax.swing.JTable();
        jTextFieldNumeroTelefone1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldDDD1 = new javax.swing.JTextField();
        jButtonIncluirTelefone1 = new javax.swing.JButton();
        jButtonExcluirTelefone1 = new javax.swing.JButton();
        jComboBoxTiposDeTelefones1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldLogradouro1 = new javax.swing.JTextField();
        jButtonIncluirEndereco1 = new javax.swing.JButton();
        jButtonExcluirEndereco1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldNumeroEndereco1 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableEndereco1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldCidade1 = new javax.swing.JTextField();
        jTextFieldPais1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldBairro1 = new javax.swing.JTextField();
        jTextFieldEstado1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jFormattedTextFieldCEP1 = new javax.swing.JFormattedTextField();
        jTextFieldComplento = new javax.swing.JTextField();
        jPanel2Email1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEmail1 = new javax.swing.JTable();
        jButtonIncluirEmail1 = new javax.swing.JButton();
        jButtonExcluirEmail1 = new javax.swing.JButton();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldClienteNumeroCNH = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldClienteCPF = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        jFormattedTextFieldClienteDataNascimento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldValidadeCNH = new javax.swing.JFormattedTextField();
        jComboBoxCategoriaCNH = new javax.swing.JComboBox<>();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTablePesquisarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "CNH", "Cat.", "Dt. Nasc."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisarClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisarCliente);
        if (jTablePesquisarCliente.getColumnModel().getColumnCount() > 0) {
            jTablePesquisarCliente.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTablePesquisarCliente.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTablePesquisarCliente.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTablePesquisarCliente.getColumnModel().getColumn(3).setPreferredWidth(15);
            jTablePesquisarCliente.getColumnModel().getColumn(4).setPreferredWidth(3);
            jTablePesquisarCliente.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyReleased(evt);
            }
        });

        jComboBoxTipoDaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "CNH", "CPF" }));

        jLabel5.setText("BUSCAR POR");

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldDDI1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTableTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDI", "DDD", "Número", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefoneMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTelefone);

        jTextFieldNumeroTelefone1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setText("DDI");

        jLabel25.setText("NÚMERO");

        jLabel26.setText("DDD");

        jLabel27.setText("TIPO");

        jTextFieldDDD1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonIncluirTelefone1.setText("INCLUIR");
        jButtonIncluirTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirTelefone1ActionPerformed(evt);
            }
        });

        jButtonExcluirTelefone1.setText("EXCLUIR");
        jButtonExcluirTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTelefone1ActionPerformed(evt);
            }
        });

        jComboBoxTiposDeTelefones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTiposDeTelefones1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldDDI1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jTextFieldDDD1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldNumeroTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTiposDeTelefones1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonIncluirTelefone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirTelefone1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDDI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDDD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxTiposDeTelefones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirTelefone1)
                    .addComponent(jButtonExcluirTelefone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Telefone", jPanel5);

        jTextFieldLogradouro1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldLogradouro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogradouro1ActionPerformed(evt);
            }
        });

        jButtonIncluirEndereco1.setText("INCLUIR");
        jButtonIncluirEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEndereco1ActionPerformed(evt);
            }
        });

        jButtonExcluirEndereco1.setText("EXCLUIR");
        jButtonExcluirEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEndereco1ActionPerformed(evt);
            }
        });

        jLabel29.setText("Lougradouro");

        jLabel30.setText("Numero");

        jTextFieldNumeroEndereco1.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldNumeroEndereco1.setPreferredSize(new java.awt.Dimension(6, 22));
        jTextFieldNumeroEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroEndereco1ActionPerformed(evt);
            }
        });

        jTableEndereco1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lougradouro", "Numero", "Bairro", "Cidade", "Estado", "Pais", "Cep", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEndereco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEndereco1MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTableEndereco1);

        jLabel31.setText("CEP");

        jLabel32.setText("Cidade");

        jLabel33.setText("Estado");

        jLabel34.setText("Pais");

        jTextFieldCidade1.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldCidade1.setPreferredSize(new java.awt.Dimension(6, 22));
        jTextFieldCidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidade1ActionPerformed(evt);
            }
        });

        jTextFieldPais1.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldPais1.setPreferredSize(new java.awt.Dimension(6, 22));

        jLabel35.setText("Bairro");

        jTextFieldBairro1.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldBairro1.setPreferredSize(new java.awt.Dimension(6, 22));
        jTextFieldBairro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairro1ActionPerformed(evt);
            }
        });

        jTextFieldEstado1.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldEstado1.setPreferredSize(new java.awt.Dimension(6, 22));

        jLabel36.setText("Complemento");

        try {
            jFormattedTextFieldCEP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP1.setText("");
        jFormattedTextFieldCEP1.setMinimumSize(new java.awt.Dimension(6, 22));
        jFormattedTextFieldCEP1.setPreferredSize(new java.awt.Dimension(34, 22));

        jTextFieldComplento.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldComplento.setPreferredSize(new java.awt.Dimension(6, 22));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jButtonIncluirEndereco1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluirEndereco1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLogradouro1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldComplento, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLogradouro1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumeroEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jTextFieldComplento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel32)))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirEndereco1)
                    .addComponent(jButtonIncluirEndereco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Endereço", jPanel6);

        jTableEmail1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmail1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableEmail1);

        jButtonIncluirEmail1.setText("INCLUIR");
        jButtonIncluirEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEmail1ActionPerformed(evt);
            }
        });

        jButtonExcluirEmail1.setText("EXCLUIR");
        jButtonExcluirEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEmail1ActionPerformed(evt);
            }
        });

        jTextFieldEmail1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmail1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Email");

        javax.swing.GroupLayout jPanel2Email1Layout = new javax.swing.GroupLayout(jPanel2Email1);
        jPanel2Email1.setLayout(jPanel2Email1Layout);
        jPanel2Email1Layout.setHorizontalGroup(
            jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Email1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Email1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                                .addComponent(jButtonIncluirEmail1)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonExcluirEmail1))
                            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Email1Layout.setVerticalGroup(
            jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIncluirEmail1)
                    .addComponent(jButtonExcluirEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Email", jPanel2Email1);

        jLabel24.setText("Data de Nasc.:");

        try {
            jFormattedTextFieldClienteCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldClienteCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldClienteCPFActionPerformed(evt);
            }
        });

        jLabel37.setText("Validade CNH");

        try {
            jFormattedTextFieldClienteDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldClienteDataNascimento.setText("");

        try {
            jFormattedTextFieldValidadeCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel22.setText("Categoria CNH:");

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel21.setText("N° CNH:");

        jLabel38.setText("Sexo:");

        jLabel23.setText("CPF:");

        jLabel8.setText("Nome Completo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTipoDaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldClienteDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldClienteNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel37)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldValidadeCNH)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoDaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldClienteNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jComboBoxCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(jFormattedTextFieldValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldClienteDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jFormattedTextFieldClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();

        if (!jTextFieldPesquisa.getText().equals("")) {
            dtm.setNumRows(0);

            String strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc;

            try {

                String texto = jTextFieldPesquisa.getText().toUpperCase();

                if (jComboBoxTipoDaPesquisa.getSelectedItem().equals("NOME")) {
                    for (int i = 0; i < alPessoaFisica.size(); i++) {

                        if (alPessoaFisica.get(i).getNome().contains(texto.toUpperCase())) {
                            strId = String.valueOf(alPessoaFisica.get(i).getId());
                            strNome = alPessoaFisica.get(i).getNome();
                            strCpf = alPessoaFisica.get(i).getCpf();
                            strCnh = alPessoaFisica.get(i).getCnh();
                            strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                            strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                            Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                            dtm.addRow(dados);
                        }
                    }
                } else if (jComboBoxTipoDaPesquisa.getSelectedItem().equals("CNH")) {
                    for (int i = 0; i < alPessoaFisica.size(); i++) {

                        if (alPessoaFisica.get(i).getCnh().contains(texto.toUpperCase())) {
                            strId = String.valueOf(alPessoaFisica.get(i).getId());
                            strNome = alPessoaFisica.get(i).getNome();
                            strCpf = alPessoaFisica.get(i).getCpf();
                            strCnh = alPessoaFisica.get(i).getCnh();
                            strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                            strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                            Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                            dtm.addRow(dados);
                        }
                    }
                } else {
                    for (int i = 0; i < alPessoaFisica.size(); i++) {

                        if (alPessoaFisica.get(i).getCpf().contains(texto.toUpperCase())) {
                            strId = String.valueOf(alPessoaFisica.get(i).getId());
                            strNome = alPessoaFisica.get(i).getNome();
                            strCpf = alPessoaFisica.get(i).getCpf();
                            strCnh = alPessoaFisica.get(i).getCnh();
                            strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                            strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                            Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                            dtm.addRow(dados);
                        }
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            dtm.setNumRows(0);
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyReleased

    private void jTablePesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisarClienteMouseClicked
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Calendar c = Calendar.getInstance();
        DefaultTableModel dtm;
        Date data;
        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
        int qtdClicks = evt.getClickCount();
        PessoaFisica pessoaFisca = new PessoaFisica();
        PessoaFisica objPessoaPesq = new PessoaFisica();

        limparTela();
        
        try {
            int idx = jTablePesquisarCliente.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTablePesquisarCliente.getSelectedRow() >= 0) {
                    dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();
                    objPessoaPesq.setId(Integer.parseInt(dtm.getValueAt(idx, 0).toString()));
                    for (int i = 0; i < alPessoaFisica.size(); i++) {
                        if (alPessoaFisica.get(i).getId() == objPessoaPesq.getId()) {

                            objPessoaPesq.setNome(alPessoaFisica.get(i).getNome());
                            objPessoaPesq.setCnh(alPessoaFisica.get(i).getCnh());
                            objPessoaPesq.setCategoriaCnh(alPessoaFisica.get(i).getCategoriaCnh());
                            objPessoaPesq.setValidadeCnh(alPessoaFisica.get(i).getValidadeCnh());
                            objPessoaPesq.setCpf(alPessoaFisica.get(i).getCpf());
                            objPessoaPesq.setDataDeNasc(alPessoaFisica.get(i).getDataDeNasc());
                            objPessoaPesq.setSexo(alPessoaFisica.get(i).getSexo());
                            objPessoaPesq.setTelefone(alPessoaFisica.get(i).getTelefone());
                            objPessoaPesq.setEmail(alPessoaFisica.get(i).getEmail());
                            objPessoaPesq.setEndereco(alPessoaFisica.get(i).getEndereco());

                            jTextFieldNome.setText(objPessoaPesq.getNome());
                            jTextFieldClienteNumeroCNH.setText(objPessoaPesq.getCnh());
                            jComboBoxCategoriaCNH.setSelectedItem(objPessoaPesq.getCategoriaCnh());
                            data = formato.parse(alPessoaFisica.get(i).getValidadeCnh());
                            c.setTime(data);
                            jFormattedTextFieldValidadeCNH.setText(df.format(c.getTime()));
                            jFormattedTextFieldClienteCPF.setText(objPessoaPesq.getCpf());
                            data = formato.parse(alPessoaFisica.get(i).getDataDeNasc());
                            c.setTime(data);
                            jFormattedTextFieldClienteDataNascimento.setText(df.format(c.getTime()));
                            jComboBoxSexo.setSelectedItem(objPessoaPesq.getSexo());

                            for (int j = 0; j < objPessoaPesq.getTelefone().size(); j++) {
                                dtm = (DefaultTableModel) jTableTelefone.getModel();
                                String ddi = String.valueOf(objPessoaPesq.getTelefone().get(j).getDdi());
                                String ddd = String.valueOf(objPessoaPesq.getTelefone().get(j).getDdd());
                                String num = String.valueOf(objPessoaPesq.getTelefone().get(j).getNumero());
                                String tipo = objPessoaPesq.getTelefone().get(j).getTipo().toString();

                                Object[] dados = {ddi, ddd, num, tipo};
                                dtm.addRow(dados);
                            }
                            for (int j = 0; j < objPessoaPesq.getEmail().size(); j++) {
                                dtm = (DefaultTableModel) jTableEmail1.getModel();

                                Object[] dados = {objPessoaPesq.getEmail().get(j).getEmail()};
                                dtm.addRow(dados);
                            }
                            for (int j = 0; j < objPessoaPesq.getEndereco().size(); j++) {
                                dtm = (DefaultTableModel) jTableEndereco1.getModel();
                                String logradouro = objPessoaPesq.getEndereco().get(j).getLogradouro();
                                String bairro = objPessoaPesq.getEndereco().get(j).getBairro();
                                String cidade = objPessoaPesq.getEndereco().get(j).getCidade();
                                String estado = objPessoaPesq.getEndereco().get(j).getEstado();
                                String pais = objPessoaPesq.getEndereco().get(j).getPais();
                                String complemento = objPessoaPesq.getEndereco().get(j).getComplemento();

                                Object[] dados = {logradouro, String.valueOf(objPessoaPesq.getEndereco().get(j).getNumero()),
                                    bairro, cidade, estado, pais, String.valueOf(objPessoaPesq.getEndereco().get(j).getCep()),
                                    complemento};
                                dtm.addRow(dados);
                            }

                            return;
                        }
                    }

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jTablePesquisarClienteMouseClicked

    private void jTableTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefoneMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableTelefone.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableTelefone.getSelectedRow() >= 0) {
                    jTextFieldDDI1.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jTextFieldDDD1.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldNumeroTelefone1.setText(String.valueOf(dtm.getValueAt(idx, 2)));

                    dtm.removeRow(idx);
                    telefones.remove(idx);

                    jTextFieldDDI1.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG18"));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableTelefoneMouseClicked

    private void jButtonIncluirTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirTelefone1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        Telefone telefone = new Telefone();
        String strDDI = jTextFieldDDI1.getText();
        String strDDD = jTextFieldDDD1.getText();
        String strNum = jTextFieldNumeroTelefone1.getText();

        if (!jTextFieldDDI1.getText().equals("") && !jTextFieldDDD1.getText().equals("") && !jTextFieldNumeroTelefone1.getText().equals("")) {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(strDDI)
                            && String.valueOf(dtm.getValueAt(i, 1)).equals(strDDD)
                            && String.valueOf(dtm.getValueAt(i, 2)).equals(strNum)) {
                        JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG19"));
                        jTextFieldDDI1.requestFocus();
                        return;
                    }
                }
            }
            try {
                if (jTextFieldDDI1.getText().length() <= 3) {
                    try {
                        telefone.setDdi(Integer.parseInt(jTextFieldDDI1.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldDDI1.setText("");
                        jTextFieldDDI1.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldDDI1.requestFocus();
                    return;
                }

                if (jTextFieldDDD1.getText().length() <= 3) {
                    try {
                        telefone.setDdd(Integer.parseInt(jTextFieldDDD1.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldDDD1.setText("");
                        jTextFieldDDD1.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldDDD1.requestFocus();
                    return;
                }

                if (jTextFieldNumeroTelefone1.getText().length() <= 10) {
                    try {
                        telefone.setNumero(Integer.parseInt(jTextFieldNumeroTelefone1.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldNumeroTelefone1.setText("");
                        jTextFieldNumeroTelefone1.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldNumeroTelefone1.requestFocus();
                    return;
                }

                telefone.setTipo((EnumTelefone) jComboBoxTiposDeTelefones1.getSelectedItem());
                telefones.add(telefone);
                Object[] dados = {jTextFieldDDI1.getText(), jTextFieldDDD1.getText(), jTextFieldNumeroTelefone1.getText(),
                    jComboBoxTiposDeTelefones1.getSelectedItem()};
                dtm.addRow(dados);

                jTextFieldDDI1.setText("");
                jTextFieldDDD1.setText("");
                jTextFieldNumeroTelefone1.setText("");
                jTextFieldDDI1.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
        }
    }//GEN-LAST:event_jButtonIncluirTelefone1ActionPerformed

    private void jButtonExcluirTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTelefone1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();

        try {
            int idx[] = jTableTelefone.getSelectedRows();
            if (jTableTelefone.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    telefones.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG18"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirTelefone1ActionPerformed

    private void jComboBoxTiposDeTelefones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTiposDeTelefones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTiposDeTelefones1ActionPerformed

    private void jTextFieldLogradouro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogradouro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLogradouro1ActionPerformed

    private void jButtonIncluirEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEndereco1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco1.getModel();
        Endereco endereco = new Endereco();
        int numeroEndereco = 0;
        int cep = 0;

        try {
            String logradouro = jTextFieldLogradouro1.getText();
            String bairro = jTextFieldBairro1.getText();
            String cidade = jTextFieldCidade1.getText();
            String estado = jTextFieldEstado1.getText();
            String pais = jTextFieldPais1.getText();
            String complemento = jTextFieldComplento.getText();

            if (!logradouro.equals("") && !jTextFieldNumeroEndereco1.getText().equals("") && !bairro.equals("")
                    && !cidade.equals("") && !estado.equals("") && !pais.equals("")) {
                try {
                    numeroEndereco = Integer.parseInt(jTextFieldNumeroEndereco1.getText());
                    cep = Integer.parseInt(jFormattedTextFieldCEP1.getText().replaceAll("-", ""));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro de conversão de dados.");
                    jTextFieldNumeroEndereco1.setText("");
                    jTextFieldNumeroEndereco1.requestFocus();
                    return;
                }

                try {
                    endereco.setLogradouro(logradouro);
                    endereco.setNumero(numeroEndereco);
                    endereco.setBairro(bairro);
                    endereco.setCidade(cidade);
                    endereco.setEstado(estado);
                    endereco.setPais(pais);
                    endereco.setCep(cep);
                    endereco.setComplemento(complemento);
                    enderecos.add(endereco);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                Object[] dados = {logradouro, String.valueOf(numeroEndereco), bairro, cidade, estado, pais, cep, complemento};
                dtm.addRow(dados);

                jTextFieldLogradouro1.setText("");
                jTextFieldNumeroEndereco1.setText("");
                jTextFieldBairro1.setText("");
                jTextFieldCidade1.setText("");
                jTextFieldEstado1.setText("");
                jTextFieldPais1.setText("");
                jFormattedTextFieldCEP1.setText("");
                jTextFieldComplento.setText("");

                jTextFieldNumeroEndereco1.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "Existem campos obrigórios que não foram preenchidos.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEndereco1ActionPerformed

    private void jButtonExcluirEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEndereco1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco1.getModel();

        try {
            int idx[] = jTableEndereco1.getSelectedRows();
            if (jTableEndereco1.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    enderecos.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEndereco1ActionPerformed

    private void jTextFieldNumeroEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroEndereco1ActionPerformed

    private void jTableEndereco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEndereco1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco1.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEndereco1.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEndereco1.getSelectedRow() >= 0) {
                    jTextFieldLogradouro1.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jTextFieldNumeroEndereco1.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldBairro1.setText(String.valueOf(dtm.getValueAt(idx, 2)));
                    jTextFieldCidade1.setText(String.valueOf(dtm.getValueAt(idx, 3)));
                    jTextFieldPais1.setText(String.valueOf(dtm.getValueAt(idx, 4)));
                    jTextFieldEstado1.setText(String.valueOf(dtm.getValueAt(idx, 5)));
                    jFormattedTextFieldCEP1.setText(String.valueOf(dtm.getValueAt(idx, 6)));
                    jTextFieldComplento.setText(String.valueOf(dtm.getValueAt(idx, 7)));

                    dtm.removeRow(idx);
                    enderecos.remove(idx);

                    jTextFieldLogradouro1.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEndereco1MouseClicked

    private void jTextFieldCidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidade1ActionPerformed

    private void jTextFieldBairro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairro1ActionPerformed

    private void jTableEmail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmail1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail1.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEmail1.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEmail1.getSelectedRow() >= 0) {
                    jTextFieldEmail1.setText(String.valueOf(dtm.getValueAt(idx, 0)));

                    dtm.removeRow(idx);
                    emails.remove(idx);

                    jTextFieldEmail1.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEmail1MouseClicked

    private void jButtonIncluirEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEmail1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail1.getModel();
        Email email = new Email();
        String campoEmail = jTextFieldEmail1.getText();

        try {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(campoEmail)) {
                        JOptionPane.showMessageDialog(this, "Email já informado para este contato");
                        jTextFieldEmail1.requestFocus();
                        return;
                    }
                }
            }

            if (!campoEmail.equals("")) {
                email.setEmail(campoEmail);
                emails.add(email);
                Object[] dados = {campoEmail};
                dtm.addRow(dados);

                jTextFieldEmail1.setText("");
                jTextFieldEmail1.requestFocus(); //coloca o cursor na caixa de texto
            } else {
                JOptionPane.showMessageDialog(null, "Informe o e-mail.");
                jTextFieldEmail1.requestFocus(); //coloca o cursor na caixa de texto
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEmail1ActionPerformed

    private void jButtonExcluirEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEmail1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail1.getModel();

        try {
            int idx[] = jTableEmail1.getSelectedRows();
            if (jTableEmail1.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    emails.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEmail1ActionPerformed

    public void limparTela(){
        //cria os objetos tabelas
        DefaultTableModel dtmEmail = (DefaultTableModel) jTableEmail1.getModel();
        DefaultTableModel dtmEnd = (DefaultTableModel) jTableEndereco1.getModel();
        DefaultTableModel dtmTel = (DefaultTableModel) jTableTelefone.getModel();
        
        //limpa as tabelas
        dtmEmail.setRowCount(0);
        dtmEnd.setRowCount(0);
        dtmTel.setRowCount(0);
        
        //limpa as caixas de textos, combobox e campos formatados
        jTextFieldNome.setText("");
        jTextFieldClienteNumeroCNH.setText("");
        jFormattedTextFieldClienteCPF.setText("");
        jFormattedTextFieldClienteDataNascimento.setText("");
        jFormattedTextFieldValidadeCNH.setText("");
//        jComboBoxSexo=null;
//        jComboBoxCategoriaCNH=null;
        
        
    }
    
    private void jTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1ActionPerformed

    private void jFormattedTextFieldClienteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldClienteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldClienteCPFActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluirEmail1;
    private javax.swing.JButton jButtonExcluirEndereco1;
    private javax.swing.JButton jButtonExcluirTelefone1;
    private javax.swing.JButton jButtonIncluirEmail1;
    private javax.swing.JButton jButtonIncluirEndereco1;
    private javax.swing.JButton jButtonIncluirTelefone1;
    private javax.swing.JComboBox<String> jComboBoxCategoriaCNH;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTipoDaPesquisa;
    private javax.swing.JComboBox<String> jComboBoxTiposDeTelefones1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP1;
    private javax.swing.JFormattedTextField jFormattedTextFieldClienteCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldClienteDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidadeCNH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2Email1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEmail1;
    private javax.swing.JTable jTableEndereco1;
    private javax.swing.JTable jTablePesquisarCliente;
    private javax.swing.JTable jTableTelefone;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldBairro1;
    private javax.swing.JTextField jTextFieldCidade1;
    private javax.swing.JTextField jTextFieldClienteNumeroCNH;
    private javax.swing.JTextField jTextFieldComplento;
    private javax.swing.JTextField jTextFieldDDD1;
    private javax.swing.JTextField jTextFieldDDI1;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEstado1;
    private javax.swing.JTextField jTextFieldLogradouro1;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumeroEndereco1;
    private javax.swing.JTextField jTextFieldNumeroTelefone1;
    private javax.swing.JTextField jTextFieldPais1;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
