/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import classesdedados.Email;
import classesdedados.Endereco;
import classesdedados.Mensagens;
import classesdedados.Pessoa;
import classesdedados.PessoaFisica;
import classesdedados.Telefone;
import classesdedados.Telefone.EnumTelefone;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persistencia.PessoaDAO;

/**
 *
 * @author renatowsilva
 */
public class TelaClientePesquisa extends javax.swing.JInternalFrame {

    PessoaDAO dao = new PessoaDAO();
    ArrayList<PessoaFisica> alPessoaFisica = new ArrayList<>();
    ArrayList<Email> emails = new ArrayList<>();
    ArrayList<Telefone> telefones = new ArrayList<>();
    ArrayList<Endereco> enderecos = new ArrayList<>();
    PessoaFisica pessoaFisica = new PessoaFisica();
    PessoaFisica objPessoaPesq = new PessoaFisica();

    /**
     * Creates new form TelaPesquisaCliente
     */
    public TelaClientePesquisa() throws Exception {
        initComponents();

        jComboBoxTiposDeTelefones.setModel(new DefaultComboBoxModel(Telefone.EnumTelefone.values()));
        jComboBoxCatCNH.setModel(new DefaultComboBoxModel(PessoaFisica.EnumCnh.values()));
        jComboBoxSexo.setModel(new DefaultComboBoxModel(PessoaFisica.EnumSexo.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarCliente = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jComboBoxTipoDaPesquisa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldDD = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTelefone = new javax.swing.JTable();
        jTextFieldNumeroTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldDDD = new javax.swing.JTextField();
        jButtonIncluirTelefone = new javax.swing.JButton();
        jButtonExcluirTelefone = new javax.swing.JButton();
        jComboBoxTiposDeTelefones = new javax.swing.JComboBox<>();
        jPanel2Email1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEmail1 = new javax.swing.JTable();
        jButtonIncluirEmail1 = new javax.swing.JButton();
        jButtonExcluirEmail1 = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonIncluirEndereco1 = new javax.swing.JButton();
        jButtonExcluirEndereco1 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableEndereco1 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jFormattedTextFieldEndNumero = new javax.swing.JFormattedTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldComplento = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        jFormattedTextFieldValidadeCNH = new javax.swing.JFormattedTextField();
        jComboBoxCatCNH = new javax.swing.JComboBox<>();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jFormattedTextFieldCNH = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTablePesquisarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "CNH", "Cat.", "Dt. Nasc."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisarClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisarCliente);
        if (jTablePesquisarCliente.getColumnModel().getColumnCount() > 0) {
            jTablePesquisarCliente.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTablePesquisarCliente.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTablePesquisarCliente.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTablePesquisarCliente.getColumnModel().getColumn(3).setPreferredWidth(15);
            jTablePesquisarCliente.getColumnModel().getColumn(4).setPreferredWidth(3);
            jTablePesquisarCliente.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyReleased(evt);
            }
        });

        jComboBoxTipoDaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "CNH", "CPF" }));
        jComboBoxTipoDaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoDaPesquisaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxTipoDaPesquisaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxTipoDaPesquisaMousePressed(evt);
            }
        });
        jComboBoxTipoDaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDaPesquisaActionPerformed(evt);
            }
        });
        jComboBoxTipoDaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxTipoDaPesquisaKeyReleased(evt);
            }
        });

        jLabel5.setText("BUSCAR POR");

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyReleased(evt);
            }
        });

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldDD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTableTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDI", "DDD", "Número", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefoneMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTelefone);

        jTextFieldNumeroTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setText("DDI");

        jLabel25.setText("NÚMERO");

        jLabel26.setText("DDD");

        jLabel27.setText("TIPO");

        jTextFieldDDD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonIncluirTelefone.setText("INCLUIR");
        jButtonIncluirTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirTelefoneActionPerformed(evt);
            }
        });

        jButtonExcluirTelefone.setText("EXCLUIR");
        jButtonExcluirTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTelefoneActionPerformed(evt);
            }
        });

        jComboBoxTiposDeTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTiposDeTelefonesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldDD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTiposDeTelefones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonIncluirTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirTelefone)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxTiposDeTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirTelefone)
                    .addComponent(jButtonExcluirTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Telefone", jPanel5);

        jTableEmail1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmail1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableEmail1);

        jButtonIncluirEmail1.setText("INCLUIR");
        jButtonIncluirEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEmail1ActionPerformed(evt);
            }
        });

        jButtonExcluirEmail1.setText("EXCLUIR");
        jButtonExcluirEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEmail1ActionPerformed(evt);
            }
        });

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel28.setText("Email");

        javax.swing.GroupLayout jPanel2Email1Layout = new javax.swing.GroupLayout(jPanel2Email1);
        jPanel2Email1.setLayout(jPanel2Email1Layout);
        jPanel2Email1Layout.setHorizontalGroup(
            jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Email1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Email1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                                .addComponent(jButtonIncluirEmail1)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonExcluirEmail1))
                            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Email1Layout.setVerticalGroup(
            jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Email1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Email1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIncluirEmail1)
                    .addComponent(jButtonExcluirEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Email", jPanel2Email1);

        jButtonIncluirEndereco1.setText("INCLUIR");
        jButtonIncluirEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEndereco1ActionPerformed(evt);
            }
        });

        jButtonExcluirEndereco1.setText("EXCLUIR");
        jButtonExcluirEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEndereco1ActionPerformed(evt);
            }
        });

        jTableEndereco1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lougradouro", "Numero", "Bairro", "Cidade", "Estado", "Pais", "Cep", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEndereco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEndereco1MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTableEndereco1);

        jLabel29.setText("Lougradouro");

        jLabel35.setText("Bairro");

        jLabel30.setText("Numero");

        jLabel36.setText("Complemento");

        jTextFieldPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaisActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel31.setText("CEP");

        jLabel32.setText("Cidade");

        jLabel33.setText("Estado");

        jLabel34.setText("Pais");

        try {
            jFormattedTextFieldEndNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEndNumero.setText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(30, 290, Short.MAX_VALUE)
                        .addComponent(jButtonIncluirEndereco1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirEndereco1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLogradouro)
                            .addComponent(jTextFieldComplento))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jFormattedTextFieldEndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextFieldComplento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel32)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirEndereco1)
                    .addComponent(jButtonIncluirEndereco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Endereço", jPanel6);

        jLabel8.setText("Nome Completo:");

        jButtonExcluir.setText("EXCLUIR CLIENTE");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("ALTERAR CLIENTE");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel23.setText("CPF:");

        jLabel24.setText("Data de Nasc.:");

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel37.setText("Validade:");

        try {
            jFormattedTextFieldValidadeCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel38.setText("Sexo:");

        try {
            jFormattedTextFieldCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNHActionPerformed(evt);
            }
        });

        jLabel21.setText("N° CNH:");

        jLabel22.setText("Categoria:");

        jButtonAtualizar.setText("BUSCAR TODOS");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTipoDaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTabbedPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCatCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoDaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButtonAtualizar))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jComboBoxCatCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(jFormattedTextFieldValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();

        if (!jTextFieldPesquisa.getText().equals("")) {
            dtm.setNumRows(0);

            String strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc;

            try {
                Object objDAO = dao.recuperar();
                alPessoaFisica = (ArrayList<PessoaFisica>) objDAO;

                String texto = jTextFieldPesquisa.getText().toUpperCase();

                if (jComboBoxTipoDaPesquisa.getSelectedItem().equals("NOME")) {
                    for (int i = 0; i < alPessoaFisica.size(); i++) {

                        if (alPessoaFisica.get(i).getNome().contains(texto.toUpperCase())) {
                            strId = String.valueOf(alPessoaFisica.get(i).getId());
                            strNome = alPessoaFisica.get(i).getNome();
                            strCpf = alPessoaFisica.get(i).getCpf();
                            strCnh = alPessoaFisica.get(i).getCnh();
                            strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                            strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                            Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                            dtm.addRow(dados);
                        }
                    }
                } else if (jComboBoxTipoDaPesquisa.getSelectedItem().equals("CNH")) {
                    for (int i = 0; i < alPessoaFisica.size(); i++) {

                        if (alPessoaFisica.get(i).getCnh().contains(texto.toUpperCase())) {
                            strId = String.valueOf(alPessoaFisica.get(i).getId());
                            strNome = alPessoaFisica.get(i).getNome();
                            strCpf = alPessoaFisica.get(i).getCpf();
                            strCnh = alPessoaFisica.get(i).getCnh();
                            strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                            strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                            Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                            dtm.addRow(dados);
                        }
                    }
                } else {
                    for (int i = 0; i < alPessoaFisica.size(); i++) {

                        if (alPessoaFisica.get(i).getCpf().contains(texto.toUpperCase())) {
                            strId = String.valueOf(alPessoaFisica.get(i).getId());
                            strNome = alPessoaFisica.get(i).getNome();
                            strCpf = alPessoaFisica.get(i).getCpf();
                            strCnh = alPessoaFisica.get(i).getCnh();
                            strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                            strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                            Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                            dtm.addRow(dados);
                        }
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            dtm.setNumRows(0);
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyReleased

    private void jTablePesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisarClienteMouseClicked
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Calendar c = Calendar.getInstance();
        DefaultTableModel dtm;
        Date data;
        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
        int qtdClicks = evt.getClickCount();
        PessoaFisica pessoaFisca = new PessoaFisica();

        limparTela();

        try {
            int idx = jTablePesquisarCliente.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTablePesquisarCliente.getSelectedRow() >= 0) {
                    dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();
                    objPessoaPesq.setId(Integer.parseInt(dtm.getValueAt(idx, 0).toString()));
                    for (int i = 0; i < alPessoaFisica.size(); i++) {
                        if (alPessoaFisica.get(i).getId() == objPessoaPesq.getId()) {

                            objPessoaPesq.setNome(alPessoaFisica.get(i).getNome());
                            objPessoaPesq.setCnh(alPessoaFisica.get(i).getCnh());
                            objPessoaPesq.setCategoriaCnh(alPessoaFisica.get(i).getCategoriaCnh());
                            objPessoaPesq.setValidadeCnh(alPessoaFisica.get(i).getValidadeCnh());
                            objPessoaPesq.setCpf(alPessoaFisica.get(i).getCpf());
                            objPessoaPesq.setDataDeNasc(alPessoaFisica.get(i).getDataDeNasc());
                            objPessoaPesq.setSexo(alPessoaFisica.get(i).getSexo());
                            objPessoaPesq.setTelefone(alPessoaFisica.get(i).getTelefone());
                            objPessoaPesq.setEmail(alPessoaFisica.get(i).getEmail());
                            objPessoaPesq.setEndereco(alPessoaFisica.get(i).getEndereco());

                            jTextFieldNome.setText(objPessoaPesq.getNome());
                            jFormattedTextFieldCNH.setText(objPessoaPesq.getCnh());
                            jComboBoxCatCNH.setSelectedItem(objPessoaPesq.getCategoriaCnh());
                            data = formato.parse(alPessoaFisica.get(i).getValidadeCnh());
                            c.setTime(data);
                            jFormattedTextFieldValidadeCNH.setText(df.format(c.getTime()));
                            jFormattedTextFieldCPF.setText(objPessoaPesq.getCpf());
                            data = formato.parse(alPessoaFisica.get(i).getDataDeNasc());
                            c.setTime(data);
                            jFormattedTextFieldDataNascimento.setText(df.format(c.getTime()));
                            jComboBoxSexo.setSelectedItem(objPessoaPesq.getSexo());

                            for (int j = 0; j < objPessoaPesq.getTelefone().size(); j++) {
                                dtm = (DefaultTableModel) jTableTelefone.getModel();
                                String ddi = String.valueOf(objPessoaPesq.getTelefone().get(j).getDdi());
                                String ddd = String.valueOf(objPessoaPesq.getTelefone().get(j).getDdd());
                                String num = String.valueOf(objPessoaPesq.getTelefone().get(j).getNumero());
                                String tipo = objPessoaPesq.getTelefone().get(j).getTipo().toString();

                                Object[] dados = {ddi, ddd, num, tipo};
                                dtm.addRow(dados);
                            }
                            telefones = objPessoaPesq.getTelefone();

                            for (int j = 0; j < objPessoaPesq.getEmail().size(); j++) {
                                dtm = (DefaultTableModel) jTableEmail1.getModel();

                                Object[] dados = {objPessoaPesq.getEmail().get(j).getEmail()};
                                dtm.addRow(dados);
                            }
                            emails = objPessoaPesq.getEmail();

                            for (int j = 0; j < objPessoaPesq.getEndereco().size(); j++) {
                                dtm = (DefaultTableModel) jTableEndereco1.getModel();
                                String logradouro = objPessoaPesq.getEndereco().get(j).getLogradouro();
                                String bairro = objPessoaPesq.getEndereco().get(j).getBairro();
                                String cidade = objPessoaPesq.getEndereco().get(j).getCidade();
                                String estado = objPessoaPesq.getEndereco().get(j).getEstado();
                                String pais = objPessoaPesq.getEndereco().get(j).getPais();
                                String complemento = objPessoaPesq.getEndereco().get(j).getComplemento();

                                Object[] dados = {logradouro, String.valueOf(objPessoaPesq.getEndereco().get(j).getNumero()),
                                    bairro, cidade, estado, pais, String.valueOf(objPessoaPesq.getEndereco().get(j).getCep()),
                                    complemento};
                                dtm.addRow(dados);
                            }
                            enderecos = objPessoaPesq.getEndereco();

                            return;
                        }
                    }

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jTablePesquisarClienteMouseClicked

    private void jTableTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefoneMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableTelefone.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableTelefone.getSelectedRow() >= 0) {
                    jTextFieldDD.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jTextFieldDDD.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldNumeroTelefone.setText(String.valueOf(dtm.getValueAt(idx, 2)));

                    dtm.removeRow(idx);
                    telefones.remove(idx);

                    jTextFieldDD.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG18"));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableTelefoneMouseClicked

    private void jButtonIncluirTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirTelefoneActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        Telefone telefone = new Telefone();
        String strDDI = jTextFieldDD.getText();
        String strDDD = jTextFieldDDD.getText();
        String strNum = jTextFieldNumeroTelefone.getText();

        if (!jTextFieldDD.getText().equals("") && !jTextFieldDDD.getText().equals("") && !jTextFieldNumeroTelefone.getText().equals("")) {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(strDDI)
                            && String.valueOf(dtm.getValueAt(i, 1)).equals(strDDD)
                            && String.valueOf(dtm.getValueAt(i, 2)).equals(strNum)) {
                        JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG19"));
                        jTextFieldDD.requestFocus();
                        return;
                    }
                }
            }
            try {
                if (jTextFieldDD.getText().length() <= 3) {
                    try {
                        telefone.setDdi(Integer.parseInt(jTextFieldDD.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldDD.setText("");
                        jTextFieldDD.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldDD.requestFocus();
                    return;
                }

                if (jTextFieldDDD.getText().length() <= 3) {
                    try {
                        telefone.setDdd(Integer.parseInt(jTextFieldDDD.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldDDD.setText("");
                        jTextFieldDDD.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldDDD.requestFocus();
                    return;
                }

                if (jTextFieldNumeroTelefone.getText().length() <= 10) {
                    try {
                        telefone.setNumero(Integer.parseInt(jTextFieldNumeroTelefone.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG20"));
                        jTextFieldNumeroTelefone.setText("");
                        jTextFieldNumeroTelefone.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG21"));
                    jTextFieldNumeroTelefone.requestFocus();
                    return;
                }

                telefone.setTipo((EnumTelefone) jComboBoxTiposDeTelefones.getSelectedItem());
                telefones.add(telefone);
                Object[] dados = {jTextFieldDD.getText(), jTextFieldDDD.getText(), jTextFieldNumeroTelefone.getText(),
                    jComboBoxTiposDeTelefones.getSelectedItem()};
                dtm.addRow(dados);

                jTextFieldDD.setText("");
                jTextFieldDDD.setText("");
                jTextFieldNumeroTelefone.setText("");
                jTextFieldDD.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
        }
    }//GEN-LAST:event_jButtonIncluirTelefoneActionPerformed

    private void jButtonExcluirTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTelefoneActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();

        try {
            int idx[] = jTableTelefone.getSelectedRows();
            if (jTableTelefone.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    telefones.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, new Mensagens().mensagem("MSG18"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirTelefoneActionPerformed

    private void jComboBoxTiposDeTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTiposDeTelefonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTiposDeTelefonesActionPerformed

    private void jButtonIncluirEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEndereco1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco1.getModel();
        Endereco endereco = new Endereco();
        int numeroEndereco = 0;
        int cep = 0;

        try {
            String logradouro = jTextFieldLogradouro.getText();
            String bairro = jTextFieldBairro.getText();
            String cidade = jTextFieldCidade.getText();
            String estado = jTextFieldEstado.getText();
            String pais = jTextFieldPais.getText();
            String complemento = jTextFieldComplento.getText();

            if (!logradouro.equals("") && !jFormattedTextFieldEndNumero.getText().equals("") && !bairro.equals("")
                    && !cidade.equals("") && !estado.equals("") && !pais.equals("")) {
                try {
                    numeroEndereco = Integer.parseInt(jFormattedTextFieldEndNumero.getText());
                    cep = Integer.parseInt(jFormattedTextFieldCEP.getText().replaceAll("-", ""));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro de conversão de dados.");
                    jFormattedTextFieldEndNumero.setText("");
                    jFormattedTextFieldEndNumero.requestFocus();
                    return;
                }

                try {
                    endereco.setLogradouro(logradouro);
                    endereco.setNumero(numeroEndereco);
                    endereco.setBairro(bairro);
                    endereco.setCidade(cidade);
                    endereco.setEstado(estado);
                    endereco.setPais(pais);
                    endereco.setCep(cep);
                    endereco.setComplemento(complemento);
                    enderecos.add(endereco);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                Object[] dados = {logradouro, String.valueOf(numeroEndereco), bairro, cidade, estado, pais, cep, complemento};
                dtm.addRow(dados);

                jTextFieldLogradouro.setText("");
                jFormattedTextFieldEndNumero.setText("");
                jTextFieldBairro.setText("");
                jTextFieldCidade.setText("");
                jTextFieldEstado.setText("");
                jTextFieldPais.setText("");
                jFormattedTextFieldCEP.setText("");
                jTextFieldComplento.setText("");

                jFormattedTextFieldEndNumero.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "Existem campos obrigórios que não foram preenchidos.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEndereco1ActionPerformed

    private void jButtonExcluirEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEndereco1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco1.getModel();

        try {
            int idx[] = jTableEndereco1.getSelectedRows();
            if (jTableEndereco1.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    enderecos.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEndereco1ActionPerformed

    private void jTableEndereco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEndereco1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco1.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEndereco1.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEndereco1.getSelectedRow() >= 0) {
                    jTextFieldLogradouro.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jFormattedTextFieldEndNumero.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldBairro.setText(String.valueOf(dtm.getValueAt(idx, 2)));
                    jTextFieldCidade.setText(String.valueOf(dtm.getValueAt(idx, 3)));
                    jTextFieldPais.setText(String.valueOf(dtm.getValueAt(idx, 4)));
                    jTextFieldEstado.setText(String.valueOf(dtm.getValueAt(idx, 5)));
                    jFormattedTextFieldCEP.setText(String.valueOf(dtm.getValueAt(idx, 6)));
                    jTextFieldComplento.setText(String.valueOf(dtm.getValueAt(idx, 7)));

                    dtm.removeRow(idx);
                    enderecos.remove(idx);

                    jTextFieldLogradouro.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEndereco1MouseClicked

    private void jTableEmail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmail1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail1.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEmail1.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEmail1.getSelectedRow() >= 0) {
                    jTextFieldEmail.setText(String.valueOf(dtm.getValueAt(idx, 0)));

                    dtm.removeRow(idx);
                    emails.remove(idx);

                    jTextFieldEmail.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEmail1MouseClicked

    private void jButtonIncluirEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEmail1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail1.getModel();
        Email email = new Email();
        String campoEmail = jTextFieldEmail.getText();

        try {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(campoEmail)) {
                        JOptionPane.showMessageDialog(this, "Email já informado para este contato");
                        jTextFieldEmail.requestFocus();
                        return;
                    }
                }
            }

            if (!campoEmail.equals("")) {
                email.setEmail(campoEmail);
                emails.add(email);
                Object[] dados = {campoEmail};
                dtm.addRow(dados);

                jTextFieldEmail.setText("");
                jTextFieldEmail.requestFocus(); //coloca o cursor na caixa de texto
            } else {
                JOptionPane.showMessageDialog(null, "Informe o e-mail.");
                jTextFieldEmail.requestFocus(); //coloca o cursor na caixa de texto
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEmail1ActionPerformed

    private void jButtonExcluirEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEmail1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail1.getModel();

        try {
            int idx[] = jTableEmail1.getSelectedRows();
            if (jTableEmail1.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    emails.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEmail1ActionPerformed

    public void limparTela() {
        //cria os objetos tabelas
        DefaultTableModel dtmEmail = (DefaultTableModel) jTableEmail1.getModel();
        DefaultTableModel dtmEnd = (DefaultTableModel) jTableEndereco1.getModel();
        DefaultTableModel dtmTel = (DefaultTableModel) jTableTelefone.getModel();

        //limpa as tabelas
        dtmEmail.setRowCount(0);
        dtmEnd.setRowCount(0);
        dtmTel.setRowCount(0);

        //limpa as caixas de textos, combobox e campos formatados
        jTextFieldNome.setText("");
        jFormattedTextFieldCNH.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldValidadeCNH.setText("");

        //limpa as caixas de textos de endereço
        jTextFieldLogradouro.setText("");
        jFormattedTextFieldEndNumero.setText("");
        jTextFieldComplento.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldPais.setText("");
        jFormattedTextFieldCEP.setText("");

    }

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        try {
            objPessoaPesq.setNome(jTextFieldNome.getText().toUpperCase());
            objPessoaPesq.setDataDeNasc(jFormattedTextFieldDataNascimento.getText());
            objPessoaPesq.setValidadeCnh(jFormattedTextFieldValidadeCNH.getText());
            objPessoaPesq.setTipo(Pessoa.EnumPessoa.FISICA);
            objPessoaPesq.setCpf(jFormattedTextFieldCPF.getText());
            objPessoaPesq.setCnh(jFormattedTextFieldCNH.getText());
            objPessoaPesq.setCategoriaCnh(Enum.valueOf(PessoaFisica.EnumCnh.class, jComboBoxCatCNH.getSelectedItem().toString()));
            objPessoaPesq.setSexo(Enum.valueOf(PessoaFisica.EnumSexo.class, jComboBoxSexo.getSelectedItem().toString()));

            objPessoaPesq.setTelefone(telefones);
            objPessoaPesq.setEmail(emails);
            objPessoaPesq.setEndereco(enderecos);

            if (jTextFieldNome.getText().equals("")) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTextFieldNome.requestFocus();
                return;
            }
            if (telefones.size() <= 0) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTabbedPane1.setSelectedIndex(0);
                jTextFieldDD.requestFocus();
                return;
            }
            if (emails.size() <= 0) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTabbedPane1.setSelectedIndex(1);
                jTextFieldEmail.requestFocus();
                return;
            }

            dao.alterar(objPessoaPesq.getId(), objPessoaPesq);
            Object objDAO = dao.recuperar();
            alPessoaFisica = (ArrayList<PessoaFisica>) objDAO;
            DefaultTableModel dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();
            dtm.setRowCount(0);
            jTextFieldPesquisa.setText("");
            limparTela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyReleased
        jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
    }//GEN-LAST:event_jTextFieldNomeKeyReleased

    private void jComboBoxTipoDaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDaPesquisaActionPerformed
    }//GEN-LAST:event_jComboBoxTipoDaPesquisaActionPerformed

    private void jComboBoxTipoDaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoDaPesquisaMouseClicked

    }//GEN-LAST:event_jComboBoxTipoDaPesquisaMouseClicked

    private void jComboBoxTipoDaPesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoDaPesquisaMousePressed
    }//GEN-LAST:event_jComboBoxTipoDaPesquisaMousePressed

    private void jComboBoxTipoDaPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxTipoDaPesquisaKeyReleased
    }//GEN-LAST:event_jComboBoxTipoDaPesquisaKeyReleased

    private void jComboBoxTipoDaPesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoDaPesquisaMouseExited
    }//GEN-LAST:event_jComboBoxTipoDaPesquisaMouseExited

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            dao.excluir(objPessoaPesq.getId());

            dao.alterar(objPessoaPesq.getId(), objPessoaPesq);
            Object objDAO = dao.recuperar();
            alPessoaFisica = (ArrayList<PessoaFisica>) objDAO;
            DefaultTableModel dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();
            dtm.setRowCount(0);
            jTextFieldPesquisa.setText("");
            limparTela();
        } catch (Exception ex) {
            Logger.getLogger(TelaClientePesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaisActionPerformed

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jFormattedTextFieldCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCNHActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTablePesquisarCliente.getModel();
        
        String strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc;
        jTextFieldPesquisa.setText("");
        try {
            dtm.setNumRows(0);
            
            Object objDAO = dao.recuperar();
            alPessoaFisica = (ArrayList<PessoaFisica>) objDAO;

            for (int i = 0; i < alPessoaFisica.size(); i++) {

                strId = String.valueOf(alPessoaFisica.get(i).getId());
                strNome = alPessoaFisica.get(i).getNome();
                strCpf = alPessoaFisica.get(i).getCpf();
                strCnh = alPessoaFisica.get(i).getCnh();
                strCatCnh = alPessoaFisica.get(i).getCategoriaCnh().toString();
                strDataNasc = alPessoaFisica.get(i).getDataDeNasc();

                Object[] dados = {strId, strNome, strCpf, strCnh, strCatCnh, strDataNasc};
                dtm.addRow(dados);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirEmail1;
    private javax.swing.JButton jButtonExcluirEndereco1;
    private javax.swing.JButton jButtonExcluirTelefone;
    private javax.swing.JButton jButtonIncluirEmail1;
    private javax.swing.JButton jButtonIncluirEndereco1;
    private javax.swing.JButton jButtonIncluirTelefone;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxCatCNH;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTipoDaPesquisa;
    private javax.swing.JComboBox<String> jComboBoxTiposDeTelefones;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNH;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldEndNumero;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidadeCNH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2Email1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEmail1;
    private javax.swing.JTable jTableEndereco1;
    private javax.swing.JTable jTablePesquisarCliente;
    private javax.swing.JTable jTableTelefone;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplento;
    private javax.swing.JTextField jTextFieldDD;
    private javax.swing.JTextField jTextFieldDDD;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumeroTelefone;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
