/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import javax.swing.DefaultComboBoxModel;
import classesdedados.Telefone;
import classesdedados.Email;
import classesdedados.Endereco;
import classesdedados.Mensagens;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import persistencia.PessoaDAO;
import classesdedados.Pessoa;
import classesdedados.PessoaFisica;
import classesdedados.PessoaJuridica;
import classesdedados.Telefone.EnumTelefone;
import java.io.IOException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vicente
 */
public class TelaCadastroDeCliente extends javax.swing.JFrame {

    ArrayList<Email> emails = new ArrayList<>();
    ArrayList<Telefone> telefones = new ArrayList<>();
    ArrayList<Endereco> enderecos = new ArrayList<>();

    /**
     * Creates new form TelaDeContatos
     */
    public TelaCadastroDeCliente() {
        initComponents();
        jComboBoxTiposDeTelefones.setModel(new DefaultComboBoxModel(Telefone.EnumTelefone.values()));
        jComboBoxTipoCNH.setModel(new DefaultComboBoxModel(PessoaFisica.EnumCnh.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonClienteSalvar = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldDDI = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTelefone = new javax.swing.JTable();
        jTextFieldNumeroTelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDDD = new javax.swing.JTextField();
        jButtonIncluirTelefone = new javax.swing.JButton();
        jButtonExcluirTelefone = new javax.swing.JButton();
        jComboBoxTiposDeTelefones = new javax.swing.JComboBox<>();
        jPanel2Email = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableEmail = new javax.swing.JTable();
        jButtonIncluirEmail = new javax.swing.JButton();
        jButtonExcluirEmail = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jButtonIncluirEndereco = new javax.swing.JButton();
        jButtonExcluirEndereco = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumeroEndereco = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableEndereco = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextAreaComplementoEndereco = new javax.swing.JTextArea();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldClienteNumeroCNH = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jFormattedTextFieldClienteCPF = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldClienteDataNascimento = new javax.swing.JFormattedTextField();
        jComboBoxTipoCNH = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable7);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane10.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("-- CADASTRO DE CLIENTES --");

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Completo:");

        jButtonClienteSalvar.setText("SALVAR");
        jButtonClienteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteSalvarActionPerformed(evt);
            }
        });

        jTabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldDDI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTableTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDI", "DDD", "Número", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefoneMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTelefone);
        if (jTableTelefone.getColumnModel().getColumnCount() > 0) {
            jTableTelefone.getColumnModel().getColumn(0).setResizable(false);
            jTableTelefone.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTableTelefone.getColumnModel().getColumn(1).setResizable(false);
            jTableTelefone.getColumnModel().getColumn(1).setPreferredWidth(2);
            jTableTelefone.getColumnModel().getColumn(2).setResizable(false);
            jTableTelefone.getColumnModel().getColumn(3).setResizable(false);
        }

        jTextFieldNumeroTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setText("DDI");

        jLabel4.setText("NÚMERO");

        jLabel3.setText("DDD");

        jLabel5.setText("TIPO");

        jTextFieldDDD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonIncluirTelefone.setText("INCLUIR");
        jButtonIncluirTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirTelefoneActionPerformed(evt);
            }
        });

        jButtonExcluirTelefone.setText("EXCLUIR");
        jButtonExcluirTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTelefoneActionPerformed(evt);
            }
        });

        jComboBoxTiposDeTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTiposDeTelefonesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTiposDeTelefones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonIncluirTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirTelefone)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jComboBoxTiposDeTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirTelefone)
                    .addComponent(jButtonExcluirTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Telefone", jPanel3);

        jTableEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmailMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableEmail);

        jButtonIncluirEmail.setText("INCLUIR");
        jButtonIncluirEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEmailActionPerformed(evt);
            }
        });

        jButtonExcluirEmail.setText("EXCLUIR");
        jButtonExcluirEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEmailActionPerformed(evt);
            }
        });

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel9.setText("Email");

        javax.swing.GroupLayout jPanel2EmailLayout = new javax.swing.GroupLayout(jPanel2Email);
        jPanel2Email.setLayout(jPanel2EmailLayout);
        jPanel2EmailLayout.setHorizontalGroup(
            jPanel2EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2EmailLayout.createSequentialGroup()
                .addGroup(jPanel2EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2EmailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2EmailLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2EmailLayout.createSequentialGroup()
                                .addComponent(jButtonIncluirEmail)
                                .addGap(6, 6, 6)
                                .addComponent(jButtonExcluirEmail))
                            .addGroup(jPanel2EmailLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2EmailLayout.setVerticalGroup(
            jPanel2EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2EmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(jPanel2EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIncluirEmail)
                    .addComponent(jButtonExcluirEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Email", jPanel2Email);

        jTextFieldLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogradouroActionPerformed(evt);
            }
        });

        jButtonIncluirEndereco.setText("INCLUIR");
        jButtonIncluirEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirEnderecoActionPerformed(evt);
            }
        });

        jButtonExcluirEndereco.setText("EXCLUIR");
        jButtonExcluirEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEnderecoActionPerformed(evt);
            }
        });

        jLabel6.setText("Lougradouro");

        jLabel7.setText("Numero");

        jTextFieldNumeroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroEnderecoActionPerformed(evt);
            }
        });

        jTableEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lougradouro", "Numero", "Bairro", "Cidade", "Estado", "Pais", "Cep", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnderecoMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableEndereco);

        jLabel11.setText("CEP");

        jLabel12.setText("Cidade");

        jLabel13.setText("Estado");

        jLabel14.setText("Pais");

        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });

        jLabel16.setText("Bairro");

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jLabel15.setText("Complemento");

        jTextAreaComplementoEndereco.setColumns(20);
        jTextAreaComplementoEndereco.setRows(5);
        jScrollPane11.setViewportView(jTextAreaComplementoEndereco);

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButtonIncluirEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluirEndereco))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPais))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirEndereco)
                    .addComponent(jButtonIncluirEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Endereço", jPanel4);

        jLabel18.setText("N° CNH:");

        jLabel19.setText("Tipo CNH:");

        jLabel20.setText("CPF:");

        try {
            jFormattedTextFieldClienteCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldClienteCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldClienteCPFActionPerformed(evt);
            }
        });

        jLabel17.setText("Data de Nascimento: ");

        try {
            jFormattedTextFieldClienteDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonClienteSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addGap(10, 10, 10)
                                        .addComponent(jFormattedTextFieldClienteDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldClienteNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxTipoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClienteNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxTipoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextFieldClienteDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jFormattedTextFieldClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClienteSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEmailActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail.getModel();

        try {
            int idx[] = jTableEmail.getSelectedRows();
            if (jTableEmail.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    emails.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEmailActionPerformed

    private void jButtonIncluirTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirTelefoneActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        Telefone telefone = new Telefone();
        String strDDI = jTextFieldDDI.getText();
        String strDDD = jTextFieldDDD.getText();
        String strNum = jTextFieldNumeroTelefone.getText();

        if (!jTextFieldDDI.getText().equals("") && !jTextFieldDDD.getText().equals("") && !jTextFieldNumeroTelefone.getText().equals("")) {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(strDDI)
                            && String.valueOf(dtm.getValueAt(i, 1)).equals(strDDD)
                            && String.valueOf(dtm.getValueAt(i, 2)).equals(strNum)) {
                        JOptionPane.showMessageDialog(this, "Telefone já informado para este contato");
                        jTextFieldDDI.requestFocus();
                        return;
                    }
                }
            }
            try {
                if (jTextFieldDDI.getText().length() <= 3) {
                    try {
                        telefone.setDdi(Integer.parseInt(jTextFieldDDI.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Informe apenas números para o DDI.");
                        jTextFieldDDI.setText("");
                        jTextFieldDDI.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Informe no máximo 3 dígitos para o DDI.");
                    jTextFieldDDI.requestFocus();
                    return;
                }

                if (jTextFieldDDD.getText().length() <= 3) {
                    try {
                        telefone.setDdd(Integer.parseInt(jTextFieldDDD.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Informe apenas números para o DDD.");
                        jTextFieldDDD.setText("");
                        jTextFieldDDD.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Informe no máximo 3 dígitos para o DDD.");
                    jTextFieldDDD.requestFocus();
                    return;
                }

                if (jTextFieldNumeroTelefone.getText().length() <= 10) {
                    try {
                        telefone.setNumero(Integer.parseInt(jTextFieldNumeroTelefone.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Informe apenas números para o telefone.");
                        jTextFieldNumeroTelefone.setText("");
                        jTextFieldNumeroTelefone.requestFocus();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Informe no máximo 10 dígitos para o telefone.");
                    jTextFieldNumeroTelefone.requestFocus();
                    return;
                }

                telefone.setTipo((EnumTelefone) jComboBoxTiposDeTelefones.getSelectedItem());
                telefones.add(telefone);
                Object[] dados = {jTextFieldDDI.getText(), jTextFieldDDD.getText(), jTextFieldNumeroTelefone.getText(),
                    jComboBoxTiposDeTelefones.getSelectedItem()};
                dtm.addRow(dados);

                jTextFieldDDI.setText("");
                jTextFieldDDD.setText("");
                jTextFieldNumeroTelefone.setText("");
                jTextFieldDDI.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_jButtonIncluirTelefoneActionPerformed

    private void jButtonExcluirTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTelefoneActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();

        try {
            int idx[] = jTableTelefone.getSelectedRows();
            if (jTableTelefone.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    telefones.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirTelefoneActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonExcluirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEnderecoActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();

        try {
            int idx[] = jTableEndereco.getSelectedRows();
            if (jTableEndereco.getSelectedRow() >= 0) {
                dtm.removeRow(idx[0]);
                for (int j = 1; j < idx.length; j++) {
                    dtm.removeRow(idx[j] - j);
                    enderecos.remove(idx[j] - j);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirEnderecoActionPerformed

    private void jTextFieldNumeroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroEnderecoActionPerformed

    private void jButtonIncluirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEnderecoActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();
        Endereco endereco = new Endereco();
        int numeroEndereco = 0;
        int cep = 0;

        try {
            String logradouro = jTextFieldLogradouro.getText();
            String bairro = jTextFieldBairro.getText();
            String cidade = jTextFieldCidade.getText();
            String estado = jTextFieldEstado.getText();
            String pais = jTextFieldPais.getText();
            String complemento = jTextAreaComplementoEndereco.getText();

            if (!logradouro.equals("") && !jTextFieldNumeroEndereco.getText().equals("") && !bairro.equals("")
                    && !cidade.equals("") && !estado.equals("") && !pais.equals("")) {
                try {
                    numeroEndereco = Integer.parseInt(jTextFieldNumeroEndereco.getText());
                    cep = Integer.parseInt(jFormattedTextFieldCEP.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro de conversão de dados.");
                    jTextFieldNumeroEndereco.setText("");
                    jTextFieldNumeroEndereco.requestFocus();
                    return;
                }

                try {
                    endereco.setLogradouro(logradouro);
                    endereco.setNumero(numeroEndereco);
                    endereco.setBairro(bairro);
                    endereco.setCidade(cidade);
                    endereco.setEstado(estado);
                    endereco.setPais(pais);
                    endereco.setCep(cep);
                    endereco.setComplemento(complemento);
                    enderecos.add(endereco);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                Object[] dados = {logradouro, String.valueOf(numeroEndereco), bairro, cidade, estado, pais, cep, complemento};
                dtm.addRow(dados);

                jTextFieldLogradouro.setText("");
                jTextFieldNumeroEndereco.setText("");
                jTextFieldBairro.setText("");
                jTextFieldCidade.setText("");
                jTextFieldEstado.setText("");
                jTextFieldPais.setText("");
                jFormattedTextFieldCEP.setText("");
                jTextAreaComplementoEndereco.setText("");

                jTextFieldNumeroEndereco.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "Existem campos obrigórios que não foram preenchidos.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEnderecoActionPerformed

    private void jComboBoxTiposDeTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTiposDeTelefonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTiposDeTelefonesActionPerformed

    private void jButtonIncluirEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirEmailActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail.getModel();
        Email email = new Email();
        String campoEmail = jTextFieldEmail.getText();

        try {
            if (dtm.getRowCount() > 0) {
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (String.valueOf(dtm.getValueAt(i, 0)).equals(campoEmail)) {
                        JOptionPane.showMessageDialog(this, "Email já informado para este contato");
                        jTextFieldEmail.requestFocus();
                        return;
                    }
                }
            }

            if (!campoEmail.equals("")) {
                email.setEmail(campoEmail);
                emails.add(email);
                Object[] dados = {campoEmail};
                dtm.addRow(dados);

                jTextFieldEmail.setText("");
                jTextFieldEmail.requestFocus(); //coloca o cursor na caixa de texto
            } else {
                JOptionPane.showMessageDialog(null, "Informe o e-mail.");
                jTextFieldEmail.requestFocus(); //coloca o cursor na caixa de texto
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirEmailActionPerformed

    private void jTextFieldLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLogradouroActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonClienteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteSalvarActionPerformed
        PessoaFisica pessoaFisica = new PessoaFisica();
        PessoaDAO contatos = new PessoaDAO();

        try {
            pessoaFisica.setNome(jTextFieldNome.getText().toUpperCase());
            pessoaFisica.setDataDeNasc(Date.valueOf(jFormattedTextFieldClienteDataNascimento.getText()));
            pessoaFisica.setTipo(Pessoa.EnumPessoa.FISICA);
            pessoaFisica.setTelefone(telefones);
            pessoaFisica.setEmail(emails);
            pessoaFisica.setEndereco(enderecos);
            pessoaFisica.setCpf(jFormattedTextFieldClienteCPF.getText());
            
            try {
                pessoaFisica.setCnh(Integer.parseInt(jTextFieldClienteNumeroCNH.getText()));
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
            }

            if (jTextFieldNome.getText().equals("")) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTextFieldNome.requestFocus();
                return;
            }
            if (telefones.size() <= 0) {
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTabbedPane.setSelectedIndex(0);
                jTextFieldDDI.requestFocus();
                return;
            }
            if(enderecos.size() <= 0){
                JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG02"));
                jTabbedPane.setSelectedIndex(2);
                jTextFieldLogradouro.requestFocus();
                return;
            }

            contatos.incluir(pessoaFisica);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, new Mensagens().mensagem("MSG14"));
        }
    }//GEN-LAST:event_jButtonClienteSalvarActionPerformed

    private void jTableTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefoneMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableTelefone.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableTelefone.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableTelefone.getSelectedRow() >= 0) {
                    jTextFieldDDI.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jTextFieldDDD.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldNumeroTelefone.setText(String.valueOf(dtm.getValueAt(idx, 2)));

                    dtm.removeRow(idx);
                    telefones.remove(idx);

                    jTextFieldDDI.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableTelefoneMouseClicked

    private void jTableEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmailMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEmail.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEmail.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEmail.getSelectedRow() >= 0) {
                    jTextFieldEmail.setText(String.valueOf(dtm.getValueAt(idx, 0)));

                    dtm.removeRow(idx);
                    emails.remove(idx);

                    jTextFieldEmail.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEmailMouseClicked

    private void jTableEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnderecoMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTableEndereco.getModel();
        int qtdClicks = evt.getClickCount();

        try {
            int idx = jTableEndereco.getSelectedRow();
            if (qtdClicks == 2) {
                if (jTableEndereco.getSelectedRow() >= 0) {
                    jTextFieldLogradouro.setText(String.valueOf(dtm.getValueAt(idx, 0)));
                    jTextFieldNumeroEndereco.setText(String.valueOf(dtm.getValueAt(idx, 1)));
                    jTextFieldBairro.setText(String.valueOf(dtm.getValueAt(idx, 2)));
                    jTextFieldCidade.setText(String.valueOf(dtm.getValueAt(idx, 3)));
                    jTextFieldPais.setText(String.valueOf(dtm.getValueAt(idx, 4)));
                    jTextFieldEstado.setText(String.valueOf(dtm.getValueAt(idx, 5)));
                    jFormattedTextFieldCEP.setText(String.valueOf(dtm.getValueAt(idx, 6)));
                    jTextAreaComplementoEndereco.setText(String.valueOf(dtm.getValueAt(idx, 7)));

                    dtm.removeRow(idx);
                    enderecos.remove(idx);

                    jTextFieldLogradouro.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor selecionar a linha que deseja excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTableEnderecoMouseClicked

    private void jFormattedTextFieldClienteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldClienteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldClienteCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClienteSalvar;
    private javax.swing.JButton jButtonExcluirEmail;
    private javax.swing.JButton jButtonExcluirEndereco;
    private javax.swing.JButton jButtonExcluirTelefone;
    private javax.swing.JButton jButtonIncluirEmail;
    private javax.swing.JButton jButtonIncluirEndereco;
    private javax.swing.JButton jButtonIncluirTelefone;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxTipoCNH;
    private javax.swing.JComboBox<String> jComboBoxTiposDeTelefones;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldClienteCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldClienteDataNascimento;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2Email;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTableEmail;
    private javax.swing.JTable jTableEndereco;
    private javax.swing.JTable jTableTelefone;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaComplementoEndereco;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldClienteNumeroCNH;
    private javax.swing.JTextField jTextFieldDDD;
    private javax.swing.JTextField jTextFieldDDI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumeroEndereco;
    private javax.swing.JTextField jTextFieldNumeroTelefone;
    private javax.swing.JTextField jTextFieldPais;
    // End of variables declaration//GEN-END:variables
}
